repos:
  - repo: https://github.com/reposense/testrepo-Delta.git
    groups:
      - group-name: code
        globs:
          - "**.java"
      - group-name: tests
        globs:
          - "src/test**"
      - group-name: docs
        globs:
          - "docs**"
          - "**.adoc"
          - "**.md"
    branches:
      - branch: master
        blurb: "My project"
        authors:
          - author-git-host-id: FH-30
            author-display-name: Francis Hodianto (FH-30)
            author-git-author-name: Francis Hodianto
            author-emails:
        ignore-authors-list:
          - jordancjq